---
title: "HPAStainR vs Single Cell Data"
author: "Tim Nieuwenhuis"
date: "5/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(HPAstainR)
```


Insert HPAStainR function and uhhh I should probably make this a package
```{r}

hpa_dat <- read.table("../normal_tissue.tsv", sep = '\t', header = TRUE, stringsAsFactors = F)

  stainR <- function(gene_list, hpa_dat,
                     cancer_dat,
                     cancer_analysis = c("Normal", "Cancer", "Both"), # weight_stain = F, weight_reliability = F,
                     tissue_level = T,
                     stringency = "normal",
                     scale_abundance= T,
                     scale_genes = T, #Do not include in shiny, this is for my personal pipeline
                     round_to = 2,
                     #subset_genes = T, #unused
                     csv_names= F,
                     stained_gene_data = T,
                     tested_protein_column = T,
                     percent_or_count = c("percent", "count", "both"),
                     drop_na_row = F){
    
    
    
    #Easy way to make cancer only work, though inefficient
    cancer_only = F
    if (cancer_analysis == "Cancer") {
      cancer_analysis ="Both"
      cancer_only = T
    }
    
    
    #Make gene list robust to incongruencies
    #test if comma seperated or non comma seperated
    
    if (!(str_detect(gene_list, ","))) {
      gene_list  <- gsub(pattern = "\\s", replacement =  ",", x =  gene_list)
      gene_list  <-   gsub(pattern = ",{2,}", replacement =  ",", x =  gene_list)
    }
    
    gene_list = gsub(pattern = " ", replacement =  "", x =  gene_list)
    gene_list = unlist(str_split(gene_list, ','))
    gene_list = toupper(gene_list)
    p_o_c = percent_or_count[1]
    
    if (tissue_level == T) {
      cell_o_tiss = "tissue_cell"
      
    }else{
      cell_o_tiss = "Cell.type"
    }
    
    #Prepare possbility of cancer
    
    
    
    
    #Remove any blanks from the gene list
    gene_list <- gene_list[gene_list != ""]
    
    
    #make new column combining cell type and tissue
    hpa_dat <- hpa_dat %>% 
      mutate(Tissue = gsub('[[:digit:]]+', '', Tissue), tissue_cell = paste0(toupper(str_trim(Tissue))," - ", Cell.type))
    
    
    #Set up all cell types for later
    all_cell_types = unique(hpa_dat[[cell_o_tiss]])
    
    #Subset just to genes of interest 
    sub_dat <- subset(hpa_dat, hpa_dat$Gene.name %in% gene_list)
    
    #Remove testis as their cell over stain and 
    sub_dat <- sub_dat %>% filter(Tissue != "testis", !is.na(Cell.type), tissue_cell != "N/A - N/A") 
    
    #Below selects the tolerance of bad data, I suggest normal or high
    if (stringency == "normal") {
      sub_dat <- subset(sub_dat, sub_dat$Reliability %in% c("Enhanced", "Supported"
                                                            #"Approved"
                                                            )) 
    }
    
    if (stringency == "high") {
      sub_dat <- subset(sub_dat, sub_dat$Reliability %in% c("Enhanced", "Approved")) 
    }
    
    
    
    
    #Test how many genes are in hpa
    percent_coding <- sum(gene_list %in% sub_dat$Gene.name)/length(gene_list)
    
    #What are the genes in the dataset
    prot_genes <- gene_list[(gene_list %in% sub_dat$Gene.name)]
    
    #What genes are not in the dataset
    non_coding <- gene_list[!(gene_list %in% sub_dat$Gene.name)]
    
    
    #Below code returns dataframe full of NAs in the case of no protein coding genes, this way you know where data is missing
    if (percent_coding == 0) {
      no_dat_matrix  <- matrix(data = NA, nrow = length(all_cell_types), ncol = 7)
      rownames(no_dat_matrix) <- all_cell_types  
      colnames(no_dat_matrix) <- c("High", "Medium", "Low", "Not detected", "enriched_score", "num_genes", "genes")
      
      
      no_dat_tib <-  as_tibble(no_dat_matrix, rownames = "cell_type" )
      
      return(no_dat_tib)
    }
    #Move above section to the end so it can react to all data
    
    
    
    #CELL TYPE ENRICHMENT
    
    #Find levels of expression in cell types
    cell_type_dat  <- table(sub_dat[[cell_o_tiss]], sub_dat$Level)
    
    cell_type_dat_df <- as.data.frame.matrix(cell_type_dat) 
    
    #WE GOTTA scale for tissues known
    #tiss_scale <- rowSums((table(sub_dat$Cell.type, sub_dat$Tissue))/length(prot_genes))
    
    #cell_type_dat_tiss_scale = cell_type_dat/tiss_scale
    
    #Normalize based on how many times they are detected
    cell_type_dat_per <-   apply(cell_type_dat, 2, FUN = function(x){x/rowSums(cell_type_dat)})
    
    
    scaled_for_genes  <- rowSums(table(sub_dat[[cell_o_tiss]],sub_dat$Gene.name))/length(prot_genes)
    
    
    
    
    
    
    #Scale for only a few genes existing
    if (scale_abundance == T) {
      #Get unique tissue counts
      uni_tiss  <- sub_dat %>% select((!!sym(cell_o_tiss)), Tissue) %>% distinct %>% arrange((!!sym(cell_o_tiss)))
      
      scaled_4_tiss_n_genes  <- scaled_for_genes/ rowSums(table(uni_tiss[[cell_o_tiss]], uni_tiss$Tissue))
      
      
      cell_type_dat_per <- cell_type_dat_per * scaled_4_tiss_n_genes
      
      #New section that fixes counts of differnt groups
      tiss_cell_percent <- sub_dat %>% select(Gene.name,Cell.type, tissue_cell) 
      
      group_list  <- table(tiss_cell_percent[[cell_o_tiss]])
      
      unique_counts <- sapply(group_list, function(x){ifelse(x/length(prot_genes) > 1, (x/length(prot_genes)), 1 )})
      
      
      cell_type_dat_per <- cell_type_dat_per/unique_counts
      
    }
    
    
    
    
    #Below add column if the low medium or high columns don't exist
    if (!("Low" %in% colnames(cell_type_dat_per))) {
      Low <- matrix(0,nrow = nrow(cell_type_dat_per))
      cell_type_dat_per <- cbind(cell_type_dat_per, Low)
      colnames(cell_type_dat_per)[ncol(cell_type_dat_per)] <- "Low"
      #DF
      Low <- matrix(0,nrow = nrow(cell_type_dat_df))
      cell_type_dat_df <- cbind(cell_type_dat_df, Low)
      colnames(cell_type_dat_df)[ncol(cell_type_dat_df)] <- "Low"
      
      
      rm(Low)
    }
    
    if (!("Medium" %in% colnames(cell_type_dat_per))) {
      Medium <- matrix(0,nrow = nrow(cell_type_dat_per))
      cell_type_dat_per <- cbind(cell_type_dat_per, Medium)
      colnames(cell_type_dat_per)[ncol(cell_type_dat_per)] <- "Medium"
      
      #DF
      Medium <- matrix(0,nrow = nrow(cell_type_dat_df))
      cell_type_dat_df <- cbind(cell_type_dat_df, Medium)
      colnames(cell_type_dat_df)[ncol(cell_type_dat_df)] <- "Medium"
      
      
      rm(Medium)
    }
    if (!("High" %in% colnames(cell_type_dat_per))) {
      High <- matrix(0,nrow = nrow(cell_type_dat_per))
      cell_type_dat_per <- cbind(cell_type_dat_per, High)
      colnames(cell_type_dat_per)[ncol(cell_type_dat_per)] <- "High"
      #DF
      High <- matrix(0,nrow = nrow(cell_type_dat_df))
      cell_type_dat_df <- cbind(cell_type_dat_df, High)
      colnames(cell_type_dat_df)[ncol(cell_type_dat_df)] <- "High"
      
      rm(High)
    }
    
    
    
    #Add all missing cell types, this allows you to see what cells there is no information for
    #This is done below by creating a matrix of NAs of the not included cells
    not_included_cells <- all_cell_types[!(all_cell_types %in% row.names(cell_type_dat_per))]
    
    not_included_matrix  <- matrix(data = NA, nrow = length(not_included_cells), ncol = ncol(cell_type_dat_per))
    
    rownames(not_included_matrix) <- not_included_cells
    
    cell_type_dat_per <- rbind(cell_type_dat_per, not_included_matrix)
    
    cell_type_dat_mat <- rbind(as.matrix(cell_type_dat_df), not_included_matrix)
    
    
    #Adding CANCER dat
    if (cancer_analysis == "Both" | cancer_analysis == "Only") {
      sub_cancer <- cancer_dat %>% filter(Gene.name %in% gene_list)
      
      sub_cancer <- sub_cancer %>% filter(!is.na(Cancer), !is.na(High))
      
      cancer_count <- sub_cancer %>% group_by(Cancer) %>% summarise(High= sum(High), Medium= sum(Medium), Low= sum(Low),
                                                                    `Not detected`= sum(Not.detected))
      cancer_per <- cancer_count
      
      cancer_per[,-1] <- (cancer_count[,-1]/rowSums(cancer_count[,-1]))
      
      cancer_count <- as.matrix(cancer_count %>% column_to_rownames(var="Cancer"))
      
      cancer_per <- as.matrix(cancer_per %>% column_to_rownames(var="Cancer"))
      
      
      if (cancer_analysis =="Both") {
        cell_type_dat_mat <- rbind(cell_type_dat_mat,cancer_count)
        cell_type_dat_per <- rbind(cell_type_dat_per,cancer_per)
        
      }
      
      
      
    }
    
    
    
    
    
    #Below is where we generate the final tibble
    cell_type_out <-  as_tibble(cell_type_dat_per, rownames = "cell_type" ) %>% #1. Make the data a tibble with rownames as cell_type
      #dplyr::arrange(desc(High), desc(Medium), desc(Low), desc(`Not detected`)) %>% #2. No longer used step
      mutate_if(is.numeric, round, round_to) %>% #3. 
      dplyr::select(cell_type, High, Medium, Low, `Not detected`) %>% #4
      mutate(enriched_score = (High * 100) + (Medium * 50) + (Low *25),
             num_genes =  sum(gene_list %in% sub_dat$Gene.name)) %>%
      arrange(desc(enriched_score)) 
    
    
    
    
    
    
    
    
    #Prepare count data for joining
    cell_type_count <- as_tibble(cell_type_dat_mat, rownames = "cell_type") %>% rename("high_expression_count" = "High", 
                                                                                       "medium_expression_count" = "Medium",
                                                                                       "low_expression_count" = "Low",
                                                                                       "not_detected_count" = "Not detected")
    
    
    cell_type_out <- left_join(cell_type_out, cell_type_count)
    
    
    
    
    #Change genes in column to only those detected
    
    #Error n here
    if (scale_genes == T) {
      prot_genes
      tiss_gene_table  <- table(sub_dat[[cell_o_tiss]],sub_dat$Gene.name) > 0.5
      #CANCER
      if (cancer_analysis == "Both") {
        cancer_gene_table  <- as.matrix(table(sub_cancer$Cancer,sub_cancer$Gene.name) > 0.5)
        #Make it robust for non matching 
        if (ncol(tiss_gene_table) != ncol(cancer_gene_table)) {
          not_shared_normal  <- colnames(cancer_gene_table)[!(colnames(cancer_gene_table) %in% colnames(tiss_gene_table))]
          not_shared_cancer  <- colnames(tiss_gene_table)[!(colnames(tiss_gene_table) %in% colnames(cancer_gene_table))]
          
          norm_add_matrix <- matrix(data= FALSE, nrow = nrow(tiss_gene_table), ncol = length(not_shared_normal))
          colnames(norm_add_matrix) <- not_shared_normal
          tiss_gene_table <- (cbind(tiss_gene_table, norm_add_matrix))
          
          
          cancer_add_matrix <- matrix(data= FALSE, nrow = nrow(cancer_gene_table), ncol = length(not_shared_cancer))
          colnames(cancer_add_matrix) <- not_shared_cancer
          cancer_gene_table <- (cbind(cancer_gene_table, cancer_add_matrix))
          
          
        }
        
        tiss_gene_table <- rbind(tiss_gene_table, cancer_gene_table)
      }
      
      cell_types_current <- cell_type_out$cell_type
      cell_types_current
      
      
      
      
      
      gene_col  <- NULL
      gene_count <- NULL
      for (cells_in in cell_types_current) {
        
        #Add grouped or split gene option here
        
        
        #cells_in <- "chondrocytes"
        if (cells_in %in% rownames(tiss_gene_table)) {
          temp_genes <- names(tiss_gene_table[cells_in,])[tiss_gene_table[cells_in,] == T]
          gene_col <-  c(gene_col, paste0(temp_genes,collapse = ", "))
          gene_count <- c(gene_count, length(temp_genes))
          
        }else{
          gene_col <- c(gene_col, "")
          gene_count <- c(gene_count, 0)
        }
        
        
        
      }
      
    }
    
    if (scale_genes == T) {
      
      cell_type_out$genes <- as.vector(gene_col)
      cell_type_out$num_genes <- gene_count
    }else{
      cell_type_out$genes <- paste0(prot_genes,collapse = ", ")
    }
    
    
    #Add the option that gives a column if a gene is availavble
    #stained_gene_data = T
    #if (stained_gene_data == T) {
    
    if (tissue_level == T) {
      staining_dat <- sub_dat %>% filter(Level != "Not detected")
      staining_tf_df <- as.matrix.data.frame(table(staining_dat$tissue_cell, staining_dat$Gene.name) > 0, T)
      colnames(staining_tf_df)  <- colnames(table(staining_dat$tissue_cell, staining_dat$Gene.name))
      staining_tf_df <- as.data.frame(staining_tf_df)
      
      #CANCER
      if (cancer_analysis == "Both" | cancer_analysis == "Only") {
        cancer_staining_dat <- sub_cancer %>% filter(High > 0 | Low > 0 | Medium > 0)
        cancer_staining_tf_df <- as.matrix.data.frame(table(cancer_staining_dat$Cancer, cancer_staining_dat$Gene.name) > 0, T)
        colnames(cancer_staining_tf_df)  <- colnames(table(cancer_staining_dat$Cancer, cancer_staining_dat$Gene.name))
        cancer_staining_tf_df <- as.data.frame(cancer_staining_tf_df)
        #put in blank information
        false_cols  <- colnames(staining_tf_df[!(colnames(staining_tf_df) %in%  colnames(cancer_staining_tf_df))])
        #make false_matrix
        false_matrix <- matrix(data = FALSE, ncol = length(false_cols), nrow = nrow(cancer_staining_tf_df))
        colnames(false_matrix) <- false_cols
        cancer_staining_tf_df <- cbind(cancer_staining_tf_df, false_matrix)
        which(colnames(cancer_staining_tf_df) %in% colnames(staining_tf_df))
        #Reorder
        new_order<- match( colnames(staining_tf_df), colnames(cancer_staining_tf_df))
        cancer_staining_tf_df<- cancer_staining_tf_df[,new_order]
        
        if (cancer_analysis == "Both") {
          staining_tf_df <- rbind(staining_tf_df, cancer_staining_tf_df)
        }
        
      }
      #Cancer end
      
    }else{
      
      staining_dat <- sub_dat %>% filter(Level != "Not detected")
      staining_tf_df <- as.matrix.data.frame(table(staining_dat$Cell.type, staining_dat$Gene.name) > 0, T)
      colnames(staining_tf_df)  <- colnames(table(staining_dat$Cell.type, staining_dat$Gene.name))
      staining_tf_df <- as.data.frame(staining_tf_df)
      
      #CANCER
      if (cancer_analysis == "Both" | cancer_analysis == "Only") {
        cancer_staining_dat <- sub_cancer %>% filter(High > 0 | Low > 0 | Medium > 0)
        cancer_staining_tf_df <- as.matrix.data.frame(table(cancer_staining_dat$Cancer, cancer_staining_dat$Gene.name) > 0, T)
        colnames(cancer_staining_tf_df)  <- colnames(table(cancer_staining_dat$Cancer, cancer_staining_dat$Gene.name))
        cancer_staining_tf_df <- as.data.frame(cancer_staining_tf_df)
        #put in blank information
        false_cols  <- colnames(staining_tf_df[!(colnames(staining_tf_df) %in%  colnames(cancer_staining_tf_df))])
        #make false_matrix
        false_matrix <- matrix(data = FALSE, ncol = length(false_cols), nrow = nrow(cancer_staining_tf_df))
        colnames(false_matrix) <- false_cols
        cancer_staining_tf_df <- cbind(cancer_staining_tf_df, false_matrix)
        which(colnames(cancer_staining_tf_df) %in% colnames(staining_tf_df))
        #Reorder
        new_order<- match( colnames(staining_tf_df), colnames(cancer_staining_tf_df))
        cancer_staining_tf_df<- cancer_staining_tf_df[,new_order]
        
        if (cancer_analysis == "Both") {
          staining_tf_df <- rbind(staining_tf_df, cancer_staining_tf_df)
        }
        
      }
      #cancer end
    }
    
    #For loop to replace T F with name
    for (col_n in 1:ncol(staining_tf_df)) {
      gene <- colnames(staining_tf_df)[col_n]
      staining_tf_df[,col_n] <- ifelse(staining_tf_df[,col_n] == T,  gene, "")
      
      #staining_tf_df %>% mutate(col_n = ifelse(col_n == T, col_n == gene, col_n == ""))
    }
    
    
    stained_list <- apply(as.matrix(staining_tf_df), 1 , paste , collapse = "," )
    #Remove all , at the end of strings
    while (sum(str_detect(string = stained_list, pattern = ",$")) > 0 ) {
      stained_list <- gsub(pattern = ",$", x= stained_list, replacement = "")
    }
    
    #Remove all , at beginning 
    while (sum(str_detect(string = stained_list, pattern = "^,")) > 0 ) {
      stained_list <- gsub(pattern = "^,", x= stained_list, replacement = "")
    }
    
    #Remove all ,, and replace with ,
    while (sum(str_detect(string = stained_list, pattern = ",,")) > 0 ) {
      stained_list <- gsub(pattern = ",,", x= stained_list, replacement = ",")
    }
    
    stained_list <- gsub(",", ", ", stained_list)
    
    stained_out <- as.data.frame(stained_list, stringsAsFactors = F) %>% rownames_to_column(var = "cell_type")
    
    cell_type_out <- left_join(cell_type_out, stained_out, by ="cell_type")
    #}
    
    
    #move stained out into upper list
    
    
    
    #Only cancer
    
    if (cancer_only == T) {
      
      cell_type_out <- cell_type_out %>% filter(cell_type %in% cancer_dat$Cancer)
      
      
      
      
    }
    
    
    ###CHI TEST HERE ###
    #Insert chi square test here, first normal data, then cancer, then both Make sure to csv names
    #filter cell type out to remove NAs
    
    
    #Remove NAs and Testis as we don't use it
    ubi_test <- hpa_dat %>% mutate(stained = ifelse(Level != "Not detected", T, F),
                                   in_list = ifelse(Gene.name %in% gene_list, T, F))  %>%
      filter(Tissue != "testis", !is.na(Cell.type), tissue_cell != "N/A - N/A") 
    #Get a list of tested genes
    genes_tested <- table(ubi_test$Gene.name)
    #Filter down to stained genes
    ubi_test_filt <- ubi_test %>% filter(stained == T)
    #Make  a table of stained proteins by cell -tisssue
    ubi_table <- table(ubi_test_filt$tissue_cell, ubi_test_filt$Gene.name)
    #Now just remove non-matching proteins
    ubi_table_filt <- ubi_table[,colnames(ubi_table) %in% rownames(genes_tested)]
    genes_tested_filt <- genes_tested[rownames(genes_tested) %in% colnames(ubi_table_filt)]
    #Create the out object which is a ratio of those stained over those tested 
    out <- (colSums(ubi_table_filt) / as.vector(genes_tested_filt))
    #Cut the data down to rare genes found in less thant the 1st quartile
    #quart_ind <- out[out <= quantile(out, .25)]
    quart_ind <- out[out <= quantile(out, .15)]
    
    ###The Chi Square calculation
    #Make quart hpa from sub hpa, necessary?
    
    #testing switching ubi test for sub hpa
    
    
    
    quart_hpa <- ubi_test %>% filter(Gene.name %in% names(quart_ind))
    
    #Not 2 levels is used to remove cell types that fail to have two levels in the gene list
    not_2_levels <- quart_hpa %>% group_by(tissue_cell) %>% summarize(stain_mean = mean(stained) , list_mean = mean(in_list)) %>% filter(stain_mean == 1 | stain_mean == 0 | list_mean == 1 | list_mean == 0)
    
    #filter down to top specificity genes
    quart_hpa <- quart_hpa %>% filter(!(tissue_cell %in% not_2_levels$tissue_cell))
    #The chi test
    
    if (nrow(quart_hpa) != 0 ) {
      chi_out <- quart_hpa %>% group_by(tissue_cell) %>%
        summarise(p_val =chisq.test(stained, in_list, simulate.p.value = T)$p.value) %>%
        rename(cell_type = tissue_cell)
      chi_out$p_val_adj <- p.adjust(chi_out$p_val)
    }
    
    
    
    #chi_out %>% arrange((p_val))
    #Re-add lost 
    #chi_out <- not_2_levels %>% mutate(p_val = 1, p_val_adj = 1) %>% select(tissue_cell, p_val, p_val_adj) %>% bind_rows(chi_out) %>%
    #            rename(cell_type = tissue_cell)
    
    if (exists("chi_out")) {
      if(cancer_analysis == "Normal"){
        cell_type_out <- left_join(cell_type_out, chi_out)
      }else{
        chi_out_tiss <- chi_out
      }
    }
    
    ####CHI SQUARE CANCER ANALYSIS
    if (cancer_analysis == "Both" | cancer_analysis == "Only") {
      sub_cell_type <- cell_type_out %>% filter(!(is.na(high_expression_count)))
      #
      sub_canc <- cancer_dat %>% filter(Cancer %in% (sub_cell_type$cell_type))  %>% unique()
      
      sub_canc <- sub_canc %>% mutate(stained = ifelse(Not.detected != 0, T, F),
                                      in_list = ifelse(Gene.name %in% gene_list, T, F))# %>%
      # filter(!(is.na(stained)))
      
      #Remove NAs and Testis as we don't use it
      ubi_test <- cancer_dat %>% mutate(stained = ifelse(Not.detected != 0, T, F),
                                        in_list = ifelse(Gene.name %in% gene_list, T, F)) 
      #Get a list of tested genes
      genes_tested <- table(ubi_test$Gene.name)
      #Filter down to stained genes
      ubi_test_filt <- ubi_test %>% filter(stained == T)
      #Make  a table of stained proteins by cell -tisssue
      ubi_table <- table(ubi_test_filt$Cancer, ubi_test_filt$Gene.name)
      #Now just remove non-matching proteins
      ubi_table_filt <- ubi_table[,colnames(ubi_table) %in% rownames(genes_tested)]
      genes_tested_filt <- genes_tested[rownames(genes_tested) %in% colnames(ubi_table_filt)]
      #Create the out object which is a ratio of those stained over those tested 
      out <- (colSums(ubi_table_filt) / as.vector(genes_tested_filt))
      #Cut the data down to rare genes found in less thant the 1st quartile
      #quart_ind <- out[out <= quantile(out, .25)]
      quart_ind <- out[out <= quantile(out, .15)]         
      
      
      quart_canc <- ubi_test %>% filter(Gene.name %in% names(quart_ind))
      
      #Not 2 levels is used to remove cell types that fail to have two levels in the gene list
      not_2_levels <- quart_canc %>% filter(!is.na(stained)) %>% group_by(Cancer) %>%
        summarize(stain_mean = mean(stained) , list_mean = mean(in_list)) %>%
        filter(stain_mean == 1 | stain_mean == 0 | list_mean == 1 | list_mean == 0)
      
      #filter down to top specificity genes
      quart_canc <- quart_canc %>% filter(!(Cancer %in% not_2_levels$Cancer))
      #The chi test
      # chi_out <- quart_canc %>% group_by(Cancer) %>%
      #   summarise(p_val =chisq.test(stained, in_list, simulate.p.value = T)$p.value) %>%
      #   rename(cell_type = Cancer)
      # 
      # chi_out$p_val_adj <- p.adjust(chi_out$p_val)
      
      if (nrow(quart_canc) != 0 ) {
        chi_out <- quart_canc %>% group_by(Cancer) %>%
          summarise(p_val =chisq.test(stained, in_list, simulate.p.value = T)$p.value) %>%
          rename(cell_type = Cancer)
        
        chi_out$p_val_adj <- p.adjust(chi_out$p_val)
      }
      
      
      
      if (cancer_analysis == "Both") {
        chi_out <- bind_rows(chi_out_tiss, chi_out)
        
        cell_type_out <- left_join(cell_type_out, chi_out)
      }else{cell_type_out <- left_join(cell_type_out, chi_out)}
      
      
    }
    
    #Fix pvalues
    #In case no pvals
    if (!("p_val" %in%colnames(cell_type_out))) {
      cell_type_out <- cell_type_out %>% mutate(p_val = 1,
                                                p_val_adj = 1)
    }
    
    cell_type_out <- cell_type_out %>% mutate(p_val = format.pval(p_val, round_to, .005),
                                              p_val_adj = format.pval(p_val_adj, round_to, .005))
    
    #Change names; might need to change once count data is incorporated
    if (csv_names == T) {
      cell_type_out <- cell_type_out %>% select(cell_type,
                                                percent_high_expression = High,
                                                high_expression_count,
                                                percent_medium_expression = Medium,
                                                medium_expression_count,
                                                percent_low_expression = Low,
                                                low_expression_count,
                                                percent_not_detected = `Not detected`,
                                                not_detected_count,
                                                number_of_proteins = num_genes,
                                                staining_score = enriched_score,
                                                tested_proteins = genes,
                                                detected_proteins = stained_list,
                                                everything())
    }
    
    if (csv_names == F) {
      cell_type_out <- cell_type_out %>% select(`Cell Type` = cell_type,
                                                `Percent High Expression` = High,
                                                `High Expression Count` = high_expression_count,
                                                `Percent Medium Expression` = Medium, 
                                                `Medium Expression Count` = medium_expression_count,
                                                `Percent Low Expression`= Low,
                                                `Low Expression Count` = low_expression_count,
                                                `Percent Not Detected` = `Not detected`,
                                                `Not Detected Count` = not_detected_count, 
                                                `Number of Proteins` = num_genes,
                                                `Staining Score` = enriched_score,
                                                `Tested Proteins` = genes,
                                                `Detected Proteins` = stained_list,
                                                `P-Value` = p_val,
                                                `P-Value Adjusted` = p_val_adj,
                                                everything())
    }
    
    #Select count percent prefernce
    if (p_o_c == "percent") {
      cell_type_out <- cell_type_out[, -grep("ount", colnames(cell_type_out))]
      
    }
    
    if (p_o_c == "count") {
      cell_type_out <- cell_type_out[, -grep("ercent", colnames(cell_type_out))]
      
    }
    
    
    if (drop_na_row == T) {
      cell_type_out <- cell_type_out %>% drop_na
    }
    
    #Simplify stained list drop  
    if (stained_gene_data == F){
      cell_type_out <- cell_type_out[, -grep("ected", colnames(cell_type_out))]
    }
    if (tested_protein_column == F){
      cell_type_out <- cell_type_out[, -grep("ested", colnames(cell_type_out))]
    }
    
    
    
    
    
    
    
    return((cell_type_out))
    
  }
  
    
  
```




```{r read in pangloa data}
dat <- read.table("PanglaoDB_markers_27_Mar_2020.tsv", sep = "\t", header = T, stringsAsFactors = F)

head(dat)

start_dat <- dat

#Remove mouse data, product description, and nickname column
dat <- dat %>% select(-ends_with("mouse"), -nicknames, -product.description) %>%
  #protein coding only and mouse exclusive
  filter(species != "Mm",gene.type == "protein-coding gene" | gene.type == "protein coding gene") %>%
  #Make data more easily jive with hpastainr such as lungs vs lung
  mutate(organ = ifelse(organ == "Lungs", "Lung", organ), organ = ifelse(organ == "Heart", "Heart Muscle", organ)) %>%
  #make comprable column to hpastainr
  mutate(stainr_col = paste0(toupper(organ), " ", tolower(cell.type)))



```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}

#So we need to loop through the stainr_col groupings
groupings <- unique(dat$stainr_col)


cell_type <- groupings[1]

final_df <- NULL
no_stain <- NULL
for (cell_type in groupings) {
  
  sub_dat <- dat %>% filter(stainr_col == cell_type)
  genes <- sub_dat$official.gene.symbol
  
  stain_result <- HPAstainR(gene_list = genes,hpa_dat = hpa_dat, cancer_analysis = "normal", csv_names = T)
  
  stain_result
  
  if (is.na(stain_result[1,2])) {
    no_stain <- c(no_stain, cell_type)
    next
  }
  
  #Make a filter to get top stainr result from a tissue
  stain_result  <- stain_result %>% mutate(tissue = str_sub(cell_type, start = 1, end = (str_locate(cell_type,"-"))[,1]  -2),
                                           stained_count = str_count(detected_proteins,",") + 1)
  
  
  top_result <- stain_result$cell_type[1]
  top_stain <- stain_result$staining_score[1]
  top_pval <- stain_result$p_val[1]
  top_adj_pval <- stain_result$p_val_adj[1]

  #Top hit within a given tissue need to make this robust to GI tract and brain
  
  #normal
  sub_stain <- stain_result %>% filter(tissue == toupper(unique(sub_dat$organ)))
  
  
  if (is.na(unique(sub_dat$organ))) {
    sub_dat$organ <- ""
  }
  
  #GI tract
  if ("GI TRACT" == toupper(unique(sub_dat$organ))) {
    
    sub_stain <- stain_result %>% filter(tissue %in% c("COLON", "DUODENUM", "RECTUM", "SMALL INTESTINE"))
  }
  
  #Blood brain barrier
  if ("BRAIN" == toupper(unique(sub_dat$organ)) | "endothelial cells (blood brain barrier)" == tolower(unique(sub_dat$cell.type))) {
    #Brain
    sub_stain <- stain_result %>% filter(tissue %in% c("CAUDATE","CEREBELLUM", "CEREBRAL CORTEX","CHOROID PLEXUS", "DORSAL RAPHE", "HIPPOCAMPUS", "HYPOTHALAMUS", "PITUITARY GLAND", "SUBSTANTIA NIGRA"))
    }
  #Eye
      if ("EYE" == toupper(unique(sub_dat$organ))) {
    
    sub_stain <- stain_result %>% filter(tissue %in% c("RETINA"))
      }
  #Breast
   if ("MAMMARY GLAND" == toupper(unique(sub_dat$organ))) {
    
    sub_stain <- stain_result %>% filter(tissue %in% c("BREAST", "LACTATING BREAST"))
    }
  
    #reproductive
   if ("REPRODUCTIVE" == toupper(unique(sub_dat$organ))) {
    
    sub_stain <- stain_result %>% filter(tissue %in% c("TESTIS", "OVARY"))
   }
      #adrenal
   if ("ADRENAL GLANDS" == toupper(unique(sub_dat$organ))) {
    
    sub_stain <- stain_result %>% filter(tissue %in% c("ADRENAL GLAND"))
   }
  
        #throid
   if ("THYROID" == toupper(unique(sub_dat$organ))) {
    
    sub_stain <- stain_result %>% filter(tissue %in% c("THYROID GLAND"))
   }
  
          #ENDOTHELIAL
   if ("endothelial cells (aorta)" == tolower(unique(sub_dat$cell.type))) {
    
    sub_stain <- stain_result %>% filter(tissue %in% c("COLON"))
    }
  
  
        #bone and blood
   if ("BONE" == toupper(unique(sub_dat$organ)) | "BLOOD" == toupper(unique(sub_dat$organ))) {
    
    sub_stain <- stain_result %>% filter(tissue %in% c("BONE MARROW"))
   }
  
     if ("OLFACTORY SYSTEM" == toupper(unique(sub_dat$organ))) {
    
    sub_stain <- stain_result %>% filter(tissue %in% c("NASOPHARYNX"))
     }
  
       if ("IMMUNE SYSTEM" == toupper(unique(sub_dat$organ))) {
    
    sub_stain <- stain_result %>% filter(tissue %in% c("BONE MARROW", "THYMUS", "LYMPH NODE", "TONSIL"))
    }
  
  
   if ("CONNECTIVE TISSUE" == toupper(unique(sub_dat$organ))) {
    #Brain
    sub_stain <- stain_result %>% filter(tissue %in% c("ADIPOSE TISSUE", "SOFT TISSUE"))
    }
  
  top_tiss_result <- sub_stain$cell_type[1]
  top_tiss_stain <- sub_stain$staining_score[1]
  top_tiss_pval <- sub_stain$p_val[1]
  top_tiss_adj_pval <- sub_stain$p_val_adj[1]
  if (nrow(sub_stain) == 0) {
    top_tiss_result <- "tissue not found"
  }
  proteins_used <- length(unique(sub_dat$official.gene.symbol))
  
  top_10_avg_prot_tested <- mean(head(stain_result$number_of_proteins))
  
  #Make confidence score to account for low protein count not being taken into account
  
  #Below is marc's version
  
  conf_score <- ifelse(proteins_used > 50, 50, proteins_used) * 0.02 * top_stain
  
  if (is.null(top_adj_pval)) {
    top_adj_pval =1.1 
    top_tiss_adj_pval =1.1
     top_pval =1.1 
    top_tiss_pval =1.1
  }
  
  temp_dat <- data.frame(cell_type, conf_score, proteins_used, top_10_avg_prot_tested, top_result, top_stain, top_pval, top_adj_pval, top_tiss_result, top_tiss_stain,top_tiss_pval, top_tiss_adj_pval, stringsAsFactors = F)
  
  final_df <- rbind(final_df, temp_dat)
}


stain_result$number_of_proteins * stain_result$percent_not_detected

#Testing stuff

length(strsplit(stain_result$tested_proteins, ",")[1])

unlist(str_split(stain_result$tested_proteins, ","))


stain_result %>% mutate(n_prot_stained = str_count(detected_proteins,",") + 1)

length(str_split(stain_result$detected_proteins, ",")[[1]])

```

Current report for Marc
```{r}

write.csv(final_df, "current_hpastainr_results_function_version.csv", row.names = F)

avail_hpa_tissue_cells = unique(stain_result$cell_type)
avail_pangloa_tissue_cells = unique(dat$stainr_col)

length(avail_hpa_tissue_cells)
length(avail_pangloa_tissue_cells)

avail_hpa_tissue_cells <- c(avail_hpa_tissue_cells, rep("", length(avail_pangloa_tissue_cells) - length(avail_hpa_tissue_cells)))

tissues_and_cells <- cbind(avail_hpa_tissue_cells, avail_pangloa_tissue_cells)

colnames(tissues_and_cells) <- c("Tissue - Cells in HPA", " Tissue - Cells in PanglaoDB")

write.csv(tissues_and_cells, "panglao_v_hpa.csv", row.names = F)

```

Do samples agreeing correlated with confidence score?
```{r}

conf_dat <- read.csv(file = "current_hpastainr_results_marked_marc_correct.csv", stringsAsFactors = F)

conf_dat$matches <- "no_match" 

conf_dat$matches[conf_dat$Match.Top == 1] <- "top_match"
conf_dat$matches[conf_dat$Match.Tiss == 1] <- "top_tissue_match"


conf_dat$matches <- factor(conf_dat$matches, levels = c("no_match", "top_tissue_match", "top_match"))

conf_dat_all_match <- filter(conf_dat, !(is.na(top_tiss_stain)))

ggplot(conf_dat_all_match) + geom_violin(aes(x=matches, y = conf_score, fill = matches)) + geom_jitter(aes(x=matches, y = conf_score))

ggplot(conf_dat) + geom_violin(aes(x=matches, y =top_stain))

ggplot(conf_dat) + geom_violin(aes(x=matches, y =top_tiss_stain))





```
Dat and HPA dat summary stats
```{r}
summ_dat <- dat %>% group_by(cell.type) %>% summarize(genes = n())

ggplot(summ_dat, aes(x=genes)) + 
  geom_histogram(color="black", fill="white") + xlab("Marker Genes Per Cell Type") +labs(title ="PanglaoDB Markers per cell type",
                                                                                            subtitle =  paste("N = ", nrow(summ_dat)))
ggsave("pangloa_markers.png")

#########

hpa_dat_new <- hpa_dat %>% 
      mutate(Tissue = gsub('[[:digit:]]+', '', Tissue), tissue_cell = paste0(toupper(str_trim(Tissue))," - ", Cell.type)) %>% distinct()

hpa_dat_sum <- hpa_dat_new %>% group_by(tissue_cell) %>%
  summarise(proteins = n(), detected = sum(!(Level %in% "Not detected")) ) %>%
  mutate(det_o_test = detected/proteins, amount_tested = ifelse(proteins <= 50, "less than or equal to 50", 
                                                          ifelse(proteins > 50 & proteins <= 700, "between 51-700",
                                                          ifelse(proteins > 700 & proteins <= 15000, "between 701-15,000",
                                                          "greater than 15,000")))) %>% filter(tissue_cell != "N/A - N/A")

ggplot(hpa_dat_sum, aes(x=(proteins))) + 
  geom_histogram(color="black", fill="white", bins=100) + xlab("Tested Proteins Per Cell Type") +
                                                          labs( title ="Human Protein Atlas Count of Tested Proteins per Cell Type",
                                                               subtitle = paste("N = ", nrow(hpa_dat_sum),"; 100 bins")) +
  geom_vline(xintercept= c(50,700, 15000), linetype = c("longdash"), color = c("blue","red", "dark green"), size = 1.2) +
  geom_segment(aes(x = c(5000), xend = c(10000), y = c(20), yend = c(20)), color = "blue" , linetype = c("longdash"), size = 1.2) +
  geom_segment(aes(x = c(5000), xend = c(10000), y = c(30), yend = c(30)), color = "red", linetype = c("longdash"), size = 1.2) +
  geom_segment(aes(x = c(5000), xend = c(10000), y = c(40), yend = c(40)), color = "dark green", linetype = c("longdash"), size = 1.2) +
  annotate(geom="text", #angle = 90, vjust = 1.3,
           size = 5,  
           x=c(7500, 7500, 7500), 
           y=c(25, 35, 45), 
           label=c("50 Protein Line", "700 Protein Line", "15000 Protein Line")
              #color="red"
          
           )

ggsave("proteins_tested.png")

ggplot(hpa_dat_sum, aes(x=detected)) + 
  geom_histogram(aes(fill =amount_tested),color="black", bins=50) + xlab("Detected Proteins Per Cell Type") +labs(title="HPA detected proteins",
                                                                                              subtitle =paste("N = ", nrow(hpa_dat_sum)))
ggsave("proteins_detected.png")


ggplot(hpa_dat_sum, aes(x=det_o_test)) + 
  geom_histogram(aes(fill =amount_tested), color="black") + xlab("Detected/Tested Proteins Per Cell Type") +labs(title="HPA detected/tested proteins",
                                                                                              subtitle =paste("N = ", nrow(hpa_dat_sum)))
ggsave("proteins_detected_divby_tested.png")


write.csv(hpa_dat_sum, "hpa_cell_type_protein_summary.csv",row.names = F)







```

Compare p-vals to go
```{r}

bonf_pval <- read.table(file = "lung_genes_bonf.txt", sep= "\t", skip = 12, header = T)


fdr_pval <- read.table(file = "lung_genes_fdr.txt", sep= "\t", skip = 11, header = T)

p_test_genes <- c("MTND1P23", "MFSD2A", "CHIAP2", "CHIA", "TNR", "SLC26A9", "PIGR", 
"C4BPA", "SFTPB", "AC008268.1", "SCN1A", "LRP2", "CCL20", "SLC6A20", 
"LAMP3", "FGFBP1", "HHIP", "FGA", "FGG", "F11", "DPCR1", "PGC", 
"ADGRF1", "ROS1", "LGI3", "SFTPC", "RP11-238K6.1", "RP11-408O19.5", 
"HKDC1", "SFTPA2", "SFTPA1", "SFTPD", "ANKRD1", "CRTAC1", "DMBT1", 
"ABCC8", "SAA1", "ELF5", "RND1", "SLC5A8", "FREM2", "CPB2", "PLA2G4F", 
"RASGRF1", "IRX6", "ALOX15B", "KRT16P2", "CSF3", "FUT3", "CXCL17", 
"NAPSA", "HAS1", "PCSK2", "LL22NC03-N95F10.1", "PLA2G3", "AGTR2", 
"SLC6A14")

p_test_out <- stainR(gene_list = p_test_genes, hpa_dat = hpa_dat, csv_names = T)


p_test_out$p_val_log10 <- -log10(p_test_out$p_val_adj)


bonf_pval$log10_pval <- -log10(bonf_pval$upload_1..P.value.)

fdr_pval$log10_pval <- -log10(fdr_pval$upload_1..FDR.)

hist(p_test_out$p_val_log10)

hist(bonf_pval$log10_pval)

hist(fdr_pval$log10_pval)
```

Testing various HPA_StainRs

```{r}
cell_type <- groupings[1]

#Current 

sub_dat <- dat %>% filter(stainr_col == cell_type)
genes <- sub_dat$official.gene.symbol

stain_result <- HPAstainR(gene_list = genes,hpa_dat = hpa_dat, cancer_analysis = F, csv_names = T)

stain_result


###

HPAstainR_test(gene_list = genes,hpa_dat = hpa_dat, cancer_analysis = F, csv_names = T)


####
stainR(gene_list = genes,hpa_dat = hpa_dat, cancer_analysis = F, csv_names = T)
```

